/* 
Problem 2 : Find the analysis of revenue generated by each customer groups of cohort years they belong to and find the corresponding revenue metrics :-
- To find the revenue metrics, we will find the corresponding days_since_first_purchase for each cohort_groups(of customerkeys & their orderdates on which the customer has ordered) from cohort_analysis view created.
- After finding the days_since_first_purchase, we will analyze the revenue generated for each day difference i.e groups within days_since_first_purchase.
- After finding the days_since_the_first_purchase which holds the most revenue and revenue_of_days_since_first_purchase_%_to_total_revenue and , we will calculate the revenue metrics till the day_since_first_purchase which holds the highest revenue & revenue_of_days_since_first_purchase_%_to_total_revenue (which in our case was the first_day_of_purchase itself).
- Then we will find the cohort_year wise distribution of total revenue, customer_count and customer_revenue of that cohort_year , for only those orderdates with days_since_first_purchase held the most revenue and revenue_of_days_since_first_purchase_%_to_total_revenue. 
*/

-- Query to analyze/check which days_after_first_purchase holds the most amount and % of revenue
WITH purchase_days AS ( -- Basically displays the total_net_revenue of each customer for each of their orderdates , and the difference of days of that customer's that orderdate from its customer's first_purchase_date, from the cohort_analysis view created earlier(from its result-set)
	SELECT
		customerkey,
		orderdate,
		total_net_revenue, -- total_net_revenue corresponding to the groups of each customers and their orderdates, i.e total revenues of all orders by the customers on that orderdate.
		orderdate - first_purchase_date AS days_since_first_purchase -- will sow the difference of days of the group(of customers and their orderdates) between their current orderdate to their first_purchase_date. 
	FROM
		cohort_analysis
)
SELECT
	days_since_first_purchase,
	SUM(total_net_revenue) AS total_revenue_for_days_since_first_purchase_diff, -- will find the sum of total_revenue for all the groups of days_since_first_purchase i.e for all no. of days of difference, where the total_net_revenue was of all the groups of customerkeys & their orderdates(i.e basically the total_net_revenue by all the customers on the orderdaytes which have that much days_since_first_purchase as shown corresponding to group) from cohort_analysis view.
	SUM(total_net_revenue) / (SELECT SUM(total_net_revenue) FROM cohort_analysis) * 100 AS percentage_of_revenue_of_days_since_first_purchase_to_total_revenue -- basically shows what % the current total_revenue_for_days_since_first_purchase makes up the the total of all the total_net_revenues for all cohort groups in cohort analysis view, i.e total revenue of all customers and their orderdates from cohort analysis table.
FROM 
	purchase_days 
GROUP BY 
	days_since_first_purchase 
ORDER BY
 days_since_first_purchase;

/* We found out here that most of the revenue generated i.e about 61% of the total revenue comes from the orders which were placed on the first day of purchase of the customers, signifying the importance of the initial purchase in driving revenue and also that there are many customers making one-time purchases and not being involved in further purchases, since the majority of the revenue is generated from the first purchase, 
So it only makes sense that we should carry out an analysis of customer groups's(cohort_year-wise) of revenue generated by customers on their first_purchase_date. */

-------------------------------------------------------

-- Query to find the total_revenue, customer_count and customer_revenue for each cohort_year which has been generated on the first_order_date for all the cohort_groups of customerkeys and their orderdates :-
SELECT
	cohort_year,
	SUM(total_net_revenue) AS total_revenue_for_cohort_year, -- will find the sum of total_net_revenue of all the groups of customerkeys for their corresponding orderdates , for all the groups whose customer's cohort_years is mentioned in the result-set's group of cohort_year mentioned previously.
	COUNT(DISTINCT customerkey) AS customer_count, -- will find all the distinct customer's count for each cohort_year.
	SUM(total_net_revenue) / COUNT(DISTINCT customerkey) AS customer_revenue -- will find like an avgerage kind of value each customer has spent over all the orders they have ordered overtime, which was found out by total_revenue_cohort_year / customer_count_cohort_year.
FROM
	cohort_analysis
WHERE -- will ensure only the sum of the total_net_revenue those gorups of customerkeys and their orderdates be taken , whose orderdates are the same as the first_purchase_date, i.e basically only finding the sum of total_net_revenue by customers on their first orderdate.
	orderdate = first_purchase_date
GROUP BY -- will group the categories on the basis of cohort years for all the customers(in the cohort groups of cohort_analysis view), and will show ther corresponding aggregated results as mentioned above for all the customerkeys falling under that cohort year corresponding to it, for their first purchase date.
	cohort_year
ORDER BY
	cohort_year;